#!/usr/bin/env bash

set -euo pipefail

CHROME_BIN="${CHROME_BIN:-/Applications/Google Chrome.app/Contents/MacOS/Google Chrome}"

convert_to=""
outdir=""
input_path=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --headless)
      shift
      ;;
    --convert-to)
      convert_to="${2:-}"
      shift 2
      ;;
    --outdir)
      outdir="${2:-}"
      shift 2
      ;;
    *)
      input_path="$1"
      shift
      ;;
  esac
done

if [ -z "$input_path" ] || [ -z "$outdir" ] || [ -z "$convert_to" ]; then
  echo "Invalid arguments for soffice fallback" >&2
  exit 1
fi

if [ "$convert_to" != "pdf" ]; then
  echo "This fallback only supports convert-to pdf" >&2
  exit 1
fi

if [ ! -f "$input_path" ]; then
  echo "Input file not found: $input_path" >&2
  exit 1
fi

if [ ! -x "$CHROME_BIN" ]; then
  echo "Google Chrome not found: $CHROME_BIN" >&2
  exit 1
fi

mkdir -p "$outdir"

temp_dir="$(mktemp -d /tmp/soffice-fallback.XXXXXX)"
cleanup() {
  rm -rf "$temp_dir"
}
trap cleanup EXIT

qlmanage -p -o "$temp_dir" "$input_path" >/dev/null 2>&1

preview_file="$(find "$temp_dir" -type f -name 'Preview.html' | head -n 1)"

if [ -z "$preview_file" ]; then
  echo "Quick Look preview not generated" >&2
  exit 1
fi

output_file="$outdir/$(basename "${input_path%.*}").pdf"

"$CHROME_BIN" \
  --headless \
  --disable-gpu \
  --allow-file-access-from-files \
  --print-to-pdf="$output_file" \
  "file://$preview_file" >/dev/null 2>&1

if [ ! -f "$output_file" ]; then
  echo "PDF not generated by Chrome print" >&2
  exit 1
fi

echo "Converted $input_path to $output_file"
